### PR TITLE
experiments to improve parsing speed

### PR DESCRIPTION
**Pull request by franzhaas**
Hi,

I am reaching out in the hope of receiving guidance and feedback.

I have here two experimental changes which are not ready to be merged, which I got motivated to try out by this documentation section.:
https://construct.readthedocs.io/en/latest/compilation.html#comparison-with-kaitai-struct

1.) Use member access instead of dictionary access, because in microbenchmarks pypy is much faster with members compared to dictionary entries. -> This breaks the tests right now... badly... 

2.) An additional element  (Select) can be compiled. This reduces the number of linkedinstances used significantly in my workload. -> Especially here I believe guidance would be helpful... 

For my workload these changes make a significant speed improvement using pypy, reducing runtime by almost 50% (real-world workload using stdf-tamer, 43s to 23s per file... and there are many files...).

I am going to think about how to pass the tests without losing the speedups for now. Most of them are about __repr__... I think I can do that...

Thanks for this awesome tool! In my environment, it is _faster_ than the HW bottleneck (the installed network connection) and faster than the Cpp implementation (which makes the mistake of waiting for the data transfer to finish before even starting...)

Best regards,
Franz

### CODE REVIEW

**Comment by arekbulski** [comment]
I will offer as much guidance and support as humanly possible.

**Comment by franzhaas** [comment]
I reduced the number of errors in the testbench... 

3 things are still open.:

1.) Compile structs into named tuples (right now, it just raises a NotImplementedError, which works... but is suboptimal)
2.) A place to store and access user-supplied functions to be able to compile constructs depending on these functions
-> just like linkedinstances/linkedbuilders/linkedparsers, but with the name linkeduserfunctions.
3.) Three more tests are failing, as the output is now written as a member (x.y), instead of a dictionary entry (x['y'])... I leave that for now.

**Comment by franzhaas** [comment]
I found a solution to store and reference the functions which have been provided by the user. This probably needs to be aligned with coding/naming standards... but it works.

The problem stopping NamedTuples form working is that an "_io" entry is in the object passed to the constructor of the NamedTuple. I do not understand where it comes from, but an ugly hack of filtering the _ starting elements out works.

@arekbulski  any hint here?

There are 4 tests still failing with the test suite.
3 are changes from x["y"] to x.y changes. -> Is it ok to change the interface to allow for the "."?

One involves cryptography and a missing "sef"... (test_encryptedsymaead)
@arekbulski any hint here?

Thanks in advance,
Franz

**Comment by arekbulski** [comment]
I wrote the compilation code many many years ago so I probably can tell you no more than you already know. I will give you a hint tho: the more complicated changes you make, the less chances are that it gets merged.

**Comment by franzhaas** [comment]
I figured most of the issues out. The test suite is now passing with only a view (but necessary) changes, as repr/str needed to be adapted to use "." instead of [] member access.

Only the non string names are still confusing me...

**Comment by arekbulski** [comment]
No dont split this PR. Let me sit on this for a while and think this through okay?

**Comment by franzhaas** [comment]
This is the speedup reachable on the workload I am currently dealing with at.

I am using stdf-tamer 1.0.28.

Please note that the user supplied functions needed to be rewritten to accept member _and_ key access to the context.

**Comment by franzhaas** [comment]
I remembered that when compiling, i have the issue that when using Rebuild, I can not provide a self-defined function, as that leads to an error. I implemented here the same change as with the IfThenElse structure.

I plan to add some tests for that...

@arekbulski I changed this back to draft, but I still would be very interesting if you believe the user visible changes and overall complexity is within reason (also you have mail...)

**Comment by franzhaas** [comment]
I think I now have a better understanding of how the "this" mechanics work, and I improved the decision process on weather to use the user function dictionary or not.

Now I don't need the function dictionary any more for my use case...

**Comment by franzhaas** [comment]
In hindsight. I aproached this the wrong way around.

The big improvements, do not come from the move from dictionaries to attributes, but from implementing more compile functionallity. However, it brings a good portion of the effort, and it is a breaking change (this.hello world vs this["hello world"] which is bad for the quality of life of users.

@arekbulski what do you think?

**Comment by arekbulski** [comment]
...and 30 commits later... :laughing: 

I warned you not to change too much at once. Now this thing is so complicated that I dont have a clue what to do with it.

**Comment by franzhaas** [comment]
> ...and 30 commits later... 😆
> 
> I warned you not to change too much at once. Now this thing is so complicated that I dont have a clue what to do with it.

Sure. I will break it up.

1.) pytest version limit.
2.1) add tests for sitations where compiled code doesnt work due to passed lambda functions
2.2.) add infrastructure which allows user supplied functions to be used in compiled code + one use case
2.3.) use this infrastructure where apropriate
3) implement more compile functionality

As I already now how to do these... I expect smooth sailing.

@arekbulski 
Apart of that... https://pycon.lt/2024/talks/FVQ9E7 I would prefer if we could split this between us, you providing insight to construct, me showing the use case and domain specific topics... (i tried to reach you on mail... as well...)

**Comment by kohlrabi** [comment]
@franzhaas I have experimented with adding __slots__ for containers a couple of months and found that performance was only increased by a miniscule amount (don't mind the date, I force pushed the rebase to current master): https://github.com/kohlrabi/construct/commit/fd38fdc12f08c577b4464ea84f6372afe0fcb579

**Comment by franzhaas** [comment]
> @franzhaas I have experimented with adding **slots** for containers a couple of months and found that performance was only increased by a miniscule amount (don't mind the date, I force pushed the rebase to current master): [kohlrabi@fd38fdc](https://github.com/kohlrabi/construct/commit/fd38fdc12f08c577b4464ea84f6372afe0fcb579)

@kohlrabi yes, this is true. The speed improvements are mainly due to.:

1.) by allowing for user supplied functions, I can use compiled constructs where I previously couldn't
2.) by compiling Constructs which previously where not compilable

The slots are high effort low result. Therefore I started over here.:

https://github.com/construct/construct/pull/1068
https://github.com/construct/construct/pull/1069

and intend not to focus on the slots.

Did I understand your commit correctly that it is focused on the "regular" constructs, not the compiled variant? Did you manage to allow for 
```python
this["1 2 3"]
```
constructs?

**Comment by kohlrabi** [comment]
@franzhaas Indeed I did not focus on the compiled variant. Improving compilation seems to be a useful way to go, very interesting. But see my edit, the change does not seem to work anymore.

**Comment by franzhaas** [comment]
I think you use pytest 8? can that be? pytest 8 does not work with construct, you need to limit to <8.0.0 https://github.com/construct/construct/pull/1068

**Comment by kohlrabi** [comment]
I used pytest8 and i worked. Just my patch does not anymore, too much seems to have changed since then.

**Comment by franzhaas** [comment]
This is odd... it does not for me... neither on the github ci nor on my machine...
does it work for you on github ci?

**Pull request closed without merging**
