### PR TITLE
pytests now also works on windows

### PR DESCRIPTION
**Pull request by timrid**
With this fix the pytest now also runs on my Windows 10 machine. The main problem is, that `/dev/zero` is not available on Windows.

The second problem is in `test_multiprocessing`, but i have not investigated further and ignored for now. This error message was thrown: 
```
FAILED tests/test_multiprocessing.py::test_multiprocessing - AttributeError: Can't pickle local object 'test_multiprocessing.<locals>.worker'
```

### CODE REVIEW

**Comment by arekbulski** [comment]
I am on the fence with this one. This library was never officially supporting Windows so your changes are kinda misdirected. I will need few days to think it through.

What I would like:
- Leave "skipif" and add a variable "onwindows" in py3compat
- Undo ZeroIO. If on windows, just dont open /dev/null
- Need to modify the .github workflows yaml to run Windows tests

**Comment by arekbulski** [comment]
Regarding multiprocessing, check this:
https://github.com/yahoo/TensorFlowOnSpark/issues/36#issuecomment-335816174

**Comment by arekbulski** [comment]
You know what, I will reimplement your changes myself because there is a lot that I would do differently. I would only ask you to do one thing for me: investigate the multiprocessing test error. Rest I will handle myself.

**Comment by timrid** [comment]
Alright. I can take a look at it this weekend.

**Comment by arekbulski** [comment]
Thanks, I really appreciate your effort. Consider this PR merged (sort of).

**Comment by timrid** [comment]
Okay, apparently the error was relatively simple.

`multiprocessing` seems to use `pickle` internally and `pickle` only works with functions at the top-level of a module. So the `worker` method has to moved to the top-level. Now it works on my windows machine.

( see also https://stackoverflow.com/a/8805244 )

**Comment by timrid** [comment]
Hmm, was it my fault that github actions is not working? 😉
https://www.githubstatus.com/incidents/s654n76c1bwr

**Comment by arekbulski** [comment]
I didnt start so I cancelled the CI job. Dont worry. I will merge your stuff later on anyway. Big thanks!

**Comment by arekbulski** [comment]
@timrid  I need your help again Timmy. Check the last commit. I added Windows to GitHub workflow and something broke. Unless we can solve this, there will be no Windows testing.

**Comment by timrid** [comment]
The problem here is, that  `export` is not available on windows. I wondered why the PYTHONPATH had to be set in the first place. That seems to me somewhat unclean. According to https://stackoverflow.com/a/11452413 it is better to make the tests as a own module (with an `__init__.py` file) and change the way the imports work in the tests a little bit.

With this changes the `export PYTHONPATH=$PYTHONPATH:'pwd'` can be removed completly from the workflow and you don't need a case distinction between ubuntu and windows .

BTW: I already stumbled over the problem once when I wanted to run the tests with vscode.... With the changes it works directly.

**Comment by arekbulski** [comment]
Ah Timmy! You saved the day once more, but who's counting!

**Comment by timrid** [comment]
You are aware that I had not yet worked on these two points?
- Use "xfail" and add a variable "onwindows" in py3compat
- Undo ZeroIO. If on windows, just dont open /dev/null

**Comment by arekbulski** [comment]
I already did them. Already told you, that I will take care of these points. ;) Check commits.

**Comment by timrid** [comment]
Just saw it. Perfect, thanks.

**Comment by arekbulski** [comment]
No, thank you! You are the hero of the day.

**Pull request merged**
