### PR TITLE
Build wheel and sdist in CI

### PR DESCRIPTION
**Pull request by pombredanne**
This adds a new job in the GitHub workflow to build
a wheel and a source distribution.
 
Reference: https://github.com/construct/construct/issues/974
Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>

### CODE REVIEW

**Comment by arekbulski** [comment]
Could you also PR a mod to the Makefile that uploads both source and a wheel?

**Comment by pombredanne** [comment]
> Could you also PR a mod to the Makefile that uploads both source and a wheel?

done!

**Comment by arekbulski** [comment]
Thank you for both. I will go over this over the weekend.

**Comment by arekbulski** [comment]
Big thanks for this. I merged the Makefile and will upload a binary distribution right after I am done with all the tickets. I am not going to accept the auto CI part, but maybe one day I will have a use for it. Big thanks again.

**Pull request closed without merging**
