### PR TITLE
Other linter complaints

### PR DESCRIPTION
**Pull request by movermeyer**
- Removed unnecessary `__init__` methods
- Removed unused variable `length` in `StringPaddedTrimmed._decode`
- Rewrote lambda + filter to list comprehension.
- Made it clear that we are intentionally only using the values of the Enum mapping while iterating.
- Removed unused `enumerate` calls

### CODE REVIEW

**Comment by arekbulski** [comment]
Small changes but why not. :) I would ask about 2 things
1. Enum could it use dict.update instead of explicit loop?
2. I prefer `filter`. Is there an advantage to a comprehension?

**Comment by movermeyer** [comment]
>Enum could it use dict.update instead of explicit loop?

Will do. It'll look like `encmapping.update({v:v for v in mapping.values()})`

>I prefer filter. Is there an advantage to a comprehension?

List comprehensions are more Pythonic, but now as I go looking, [it's apparently a divisive topic](https://stackoverflow.com/a/3013722). In this case, I find the list comprehension easier, and I was prompted by pylint considering it a smell (See [deprecated-lambda (W0110)](https://pylint.readthedocs.io/en/latest/reference_guide/features.html))

**Comment by arekbulski** [comment]
Yeah its a religious issue indeed \o/... I would prefer a filter cause it looks clearer to me, but that is just me "owning it". No real arguments. I dont consider pylint suggestions as value in itself. How about you revert that one just out of courtesy for myself and we leave it at that? :wink:

**Comment by movermeyer** [comment]
😄 Of course. No worries. 

You are the maintainer and therefore you have the final say.

**Pull request merged**
