### PR TITLE
Fix pickling

### LINKED ISSUE #249: Use Container class with multiprocessing.Queue()
Is the Container class supported in multiprocessing Queue? We have been using Container with the general Queue in a multithreading program.   Once the system was converted from multithreading to multiprocessing (which required multiprocessing.Queue), we can no longer get the Container instance from the multiprocessing.Queue(). 

Section of the reported error is shown here: 

``` py
  File "C:\Python27\python-2.7.4\lib\multiprocessing\queues.py", line 117, in get
    res = self._recv()
  File "C:\Python27\python-2.7.4\lib\site-packages\construct\lib\container.py", line 67, in __setitem__
    self.__keys_order__.append(key)
  File "C:\Python27\python-2.7.4\lib\site-packages\construct\lib\container.py", line 63, in __getattr__
    raise AttributeError(name)
AttributeError: __keys_order__
```

### PR DESCRIPTION
**Pull request by domenzain**
Reset explicitly all state-related variables and apply the supplied state.
Also add an inner Container to the pickling test.

This should fix #249.

### CODE REVIEW

**Comment by arekbulski** [comment]
Looks good. Can you telll why calling the init doesnt work?

**Comment by domenzain** [comment]
The attributes are already automatically pickled.

And they are unpickled before any of the `__slots__` are re-established.
So before `__keys_order__` is even set. So when performing the update nothing is actually updated and the `__keys_order__` is incorrect.

Thinking more carefully about it, it should be better to simply re-establish the order, which is really the only stateful thing in `Container`s. Then there is no need to update the dictionary explicitly.

**Comment by arekbulski** [comment]
This doesnt explain why calling `__init__` ctor doesnt work.

Cant simply restore state because Container inherits from dict. Its not a matter of simply assigning fields.

**Comment by domenzain** [comment]
In `Container`'s  `__setitem__`, the `__keys_order__` is **only** updated if the key is **not** already in the dictionaries attributes.

For `__init__` to work (which itself uses `__setitem__`), the dictionary needs to be empty. Otherwise the order in `__keys_order__` is never set for keys that are already present and the resulting unpickled class is not the same as the original one.

**Pull request merged**
