### PR TITLE
Add tox support for local testing

### PR DESCRIPTION
**Pull request by catlee**

### CODE REVIEW

**Comment by arekbulski** [comment]
I am not familiar with TOX. What does it do?

**Comment by catlee** [comment]
Tox is a way to automate and standardize test environments for python.
http://tox.readthedocs.io/en/latest/

I've found it very useful to test multiple versions of python against my code locally.

**Comment by arekbulski** [comment]
How do I make use of this change?

**Comment by catlee** [comment]
To use it locally, create a fresh virtual environment, then run `pip install tox`.

After that you can run 'tox' and it will run all the tests for each of the specified environments.

**Comment by catlee** [comment]
See also https://www.hackzine.org/even-better-testing-with-pytest-tox-travis.html for example for how you can combine these together with travis.

**Comment by arekbulski** [comment]
I dont see a point in using tox on Travis, since Travis already works just fine. But if this is gonna be convenient to you, ill just add it.

**Pull request merged**
