### PR TITLE
remove py2-related hacks, mark some functions as deprecated

### PR DESCRIPTION
**Pull request by denballakh**
The only thing that changes: fields like `b"_foo"` are no longer considered "private". But I don't think anybody uses bytes-named fields.

### CODE REVIEW

**Comment by denballakh** [comment]
Things marked as deprecated in py3compat module are not used anywhere else in the library. 
They can be removed by deleting them from `py3compat.py` module and removing corresponding lines from `construct.lib.__init__.__all__` list.

I tested this change on 3.8 and 3.12.

**Comment by arekbulski** [comment]
CI is green as well, good job.

**Comment by denballakh** [comment]
Don't merge. 
There are several places where `bytes` objects are no longer accepted. 
I will review these changes later, fix problems and probably add tests to ensure the behaviour.

**Comment by arekbulski** [comment]
Understood.

**Comment by arekbulski** [comment]
Feel free to request my assistance if you want.

**Comment by denballakh** [comment]
I'm looking again at these changes and noticed some weird things:

```py
>>> c = Computed(42)
>>> x = Struct(b'bytes' / c, 'str' / c, 42 / c)
>>> x.parse(b'')
Container(b'bytes'=42, str=42, 42=42)
```
`Container.__repr__` definitely shouldn't work like that.
Not sure about non-str named constructs. Should they work? I think it makes sense if name is hashable. Yes, it won't work nicely with lambdas like `this.42` or `this.b'...'`, but I dont see a reason to forbid such names for constructs. Values are still obtainable from contexts using item access: `con[42]` or `con[b'...']`


Backwards incompatible changes:
- `d * b'docs'` no longer works, it raises error. I think it is good, I doubt anyone was manually replacing `'docs'` with `b'docs'` in their code.
- In `TimeStamp`: `unit` and `epoch` of type `bytes` are no longer accepted. If this is not good - let me know.
- `LazyContainer[bytes]` might not work as expected. I think this is related to non-str construct names I mentioned earlier. CI is green, so i think this is ok.
- thing i mentioned initially: fields like `b"_foo"` are no longer considered "private"

Everything else should be fine.

**Comment by arekbulski** [comment]
All those changes are okay. Especially the non str struct field names.

**Comment by denballakh** [comment]
Ok. Then feel free to merge this PR. I don't think we need any additional tests.

I think `Container.__repr__` should be changed anyway (if there are non-str fields, normal containers should stay as is). I will provide a fix for it later.

There is a merge conflict. I will try to resolve it, if i have enough permissions

**Comment by arekbulski** [comment]
I will merge this PR tomorrow. Good job. :+1:

**Pull request merged**
