### PR TITLE
Improve docs for Bit-related constructs

### PR DESCRIPTION
**Pull request by yannayl**
@arekbulski as promised - more examples without using the `Bitwise` construct

I couldn't find how to update the rst files. Are they updated automatically?

### CODE REVIEW

**Comment by arekbulski** [comment]
The docs/*.rst are source. After you modify them you need to use `make html` on your local computer to build it locally or Rebuild new version on the Read the docs site. 

See? "Build Version" button
Zrzut ekranu z 2021-03-28 19-24-26

**Comment by arekbulski** [comment]
What just pisses me off is that GitHub does not do soft wrap. You write infinite lines, I like it, I really do. I do that myself. But then I cant read it properly. Will have to check out this `gh pr` command and download it my computer for review. 

Tell me when you are done. Then I will review it.

**Comment by arekbulski** [comment]
I like your patch mostly. However... you seem to be overusing the term bit-level endianness. Please remember that this term exists only between you and me. Its not an established term in general. 

Also I dont like one line. I liked mine more:
    Byte ordering refers to bytes (chunks of 8 bits) so, for example::
    Byte ordering (i.e. `swapped` parameter) refers to byte-level endianness, for example::

There is no byte-level endianness as far rest of the world see it. Its just endianness.

**Comment by yannayl** [comment]
> I like your patch mostly. However... you seem to be overusing the term bit-level endianness. Please remember that this term exists only between you and me. Its not an established term in general.
> 
> Also I dont like one line. I liked mine more:
> Byte ordering refers to bytes (chunks of 8 bits) so, for example::
> Byte ordering (i.e. `swapped` parameter) refers to byte-level endianness, for example::
> 
> There is no byte-level endianness as far rest of the world see it. Its just endianness.

I took it straight from Wikipedia entry on Endianness. But I wasn't familiar with it before, so I assumed it's a problem on my end.
I will rephrase somehow

**Comment by arekbulski** [comment]
Hmm yeah, the language needs some work. But I have confidence you will get it right.

**Comment by yannayl** [comment]
Usually when documenting I just think "what would future me want to see here".

**Comment by yannayl** [comment]
Updated. @arekbulski 

I removed the `bit level endianness` term wherever I could. Or put it in brackets.
The only place I left it as is was in the comments on the examples. I think that it is very clear and concise in that specific context

**Comment by arekbulski** [comment]
>  Note that by default the bit ordering is from MSB to LSB for every byte (i.e. bit-level little-endian)...

Wrong. By default its byte-big bit-big endianness.

> d = ByteSwapped(BitsInteger(16)) # Byte-Level Little-Endian, Bit-Level Little-Endian

Wrong. Its byte-big bit-little endian.

> d = ByteSwapped(BitsInteger(16, swapped=True)) # Byte-Level Big-Endian, Bit-Level Little-Endian

Wrong. Its byte-little and bit-little endian.

**Comment by yannayl** [comment]
> > Note that by default the bit ordering is from MSB to LSB for every byte (i.e. bit-level little-endian)...
> 
> Wrong. By default its byte-big bit-big endianness.
> 
> > d = ByteSwapped(BitsInteger(16)) # Byte-Level Little-Endian, Bit-Level Little-Endian
> 
> Wrong. Its byte-big bit-little endian.
> 
> > d = ByteSwapped(BitsInteger(16, swapped=True)) # Byte-Level Big-Endian, Bit-Level Little-Endian
> 
> Wrong. Its byte-little and bit-little endian.

Conclusion: don't PR when you have a cold and you don't think straight :/ at least it's not covid

**Comment by arekbulski** [comment]
Get better. ;) As for the PR, do you want me to take over? If so just tell me if I was right on the 3 cases and I will take over.

**Comment by yannayl** [comment]
I think you are right on the 

> > Note that by default the bit ordering is from MSB to LSB for every byte (i.e. bit-level little-endian)...
> 
> Wrong. By default its byte-big bit-big endianness.
You are right.

> > d = ByteSwapped(BitsInteger(16)) # Byte-Level Little-Endian, Bit-Level Little-Endian
> 
> Wrong. Its byte-big bit-little endian.

I think I am actually right here. The first Byte (bits 0-7) is the 5 which is the least significant byte and therefore it's Byte level little endian.

> > d = ByteSwapped(BitsInteger(16, swapped=True)) # Byte-Level Big-Endian, Bit-Level Little-Endian
> 
> Wrong. Its byte-little and bit-little endian.
I think here I'm also right.

**Comment by yannayl** [comment]
Yes, take over it please. I need more tea and more sleep. Sorry

**Comment by arekbulski** [comment]
Dang. You were right about those last 2 cases.

**Pull request merged**
