### PR TITLE
Docs and tests for in operator using lambda and this

### PR DESCRIPTION
**Pull request by potens1**

### CODE REVIEW

**Comment by arekbulski** [comment]
Please move the unit test, `this expression` is in a different test script. Otherwise good.

**Comment by arekbulski** [comment]
Ah split it, and xfail the one using `this`. It CANNOT pass (pun unintended).

**Comment by arekbulski** [comment]
Split it into 2, only 1 should be xfailed.

**Comment by potens1** [comment]
Do you mean one case with the "this", and another one for the lambda context ?

In this case, should the test for the context be back to test_all.py

**Comment by arekbulski** [comment]
Yes (one for this, one for lambda) and No (dont move back to _all).

**Pull request merged**
