### PR TITLE
Don't hide Exceptions in Range._build

### PR DESCRIPTION
**Pull request by beardypig**
Exceptions are hidden when building a Range object. I was having some problems debugging until I worked it out :)

### CODE REVIEW

**Comment by arekbulski** [comment]
Oh wow, you found quite a bug. This wasnt intentional. Good job. 

I am thinking that maybe it should put into context something called "lastbuilt" that has index of last successful element build and turns into "all" after last was done. What do you think? Would it be helpful?

**Comment by arekbulski** [comment]
Also parse has a similar piece of code. Is there something we should fix there too?

**Comment by beardypig** [comment]
lastbuilt in the context would be quite useful, sometimes it is hard to debug where an error happened :) 

Looks like `_parse` will also hide an exception. I'm not exactly sure when `stream.seek(fallback)` should be called? Should it be called even before `raise RangeError`?

**Comment by arekbulski** [comment]
I have no idea. Spent too much time on other projects and now I forgot how this thing even works /o\.

**Comment by beardypig** [comment]
Ha, OK. How about this?

**Comment by arekbulski** [comment]
You fixed CAP, great. Looks all correct now.

**Comment by beardypig** [comment]
Now even more tests fail! whoops :D

**Comment by arekbulski** [comment]
Ha ha, yeah you broke it, man!

**Comment by beardypig** [comment]
Yeah, guess it just stops at an exception :) OK undone that commit :)

**Comment by beardypig** [comment]
Is this good to merge?

**Pull request merged**
