### PR TITLE
add exception kwarg to various validation constructs

### PR DESCRIPTION
**Pull request by Evidlo**
Checksum, Check, Const, Validator, ExprValidator, OneOf, NoneOf

### CODE REVIEW

**Comment by arekbulski** [comment]
I would likely reject this PR. I appreciate anyone taking effort to submit something, anything to the codebase but please understand that I dont like this idea of runtime-provided exception types. Expanding the set of error types, for each class, is fine. This is how Construct does it. But runtime exceptino types is meh. If you would like to go that way, please dont change this PR but create a new one.

**Comment by Evidlo** [comment]
Can I at least split the exceptions out into a separate `_exception` function so that the constructs can be subclassed and `_exception` overriden without rewriting all of `_parse`?

**Comment by Evidlo** [comment]
I don't quite understand what you mean.  Suppose I have this structure:

``` python
foo = Struct(
    "data1" / Bytes(8),
    "check1" / Checksum(Bytes(8), my_hash, this.data1),
    "data2" / Bytes(8),
    "check2" / Checksum(Bytes(8), my_hash, this.data2)
)
```

How do you catch an exception in `check1` vs `check2`?

**Comment by arekbulski** [comment]
Ah right. You dont. There are different exceptions for different classes, but in current implementation there is no means of distinguishing individual fields in a struct. Now I see your point. It would be nice if you would suggest (and then implement) some solution to that, but what you proposed earlier, I just dont like it, its not consistent with existing design and its bloating the codebase.

**Comment by Evidlo** [comment]
There's really only 3 solutions with the current codebase:

1. allow an `exception` kwarg for the classes that do checks.
2. move the exception raising into an `_exception` function
3. make the current `path` available in the raised exception

The first two are the same mentioned previously.

I don't think the third way is great because `path` isn't well documented and isn't available in certain places where exceptions are raised.

**Comment by arekbulski** [comment]
I think I would prefer the third solution, if any.

**Comment by Evidlo** [comment]
I've been considering extending `ConstructError` like so:
``` python
class ConstructError(Exception):
    def __init__(self, message, path=None):
        self.path = path
        if path is None:
            super(ConstructError, self).__init__(message)
        else:
            message = "Error in path {}\n".format(path) + message
            super(ConstructError, self).__init__(message)
```

Exceptions would be much easier to debug because you would have the full path that the exception occured in.

I'd also like to add a `path` argument to `stream_read`, `stream_read_entire`, `stream_write`, `stream_seek` and `stream_tell`, so that the path information is available when a `StreamError` is raised.

```
StreamError: Error in path (parsing) -> data
stream read less than specified amount, expected 12884901892, found 74
```

**Comment by Evidlo** [comment]
Is this an acceptable solution?

**Comment by arekbulski** [comment]
I like this 3rd path approach. Lets contemplate on this. Are you up to writing a PR?

**Comment by arekbulski** [comment]
> I'd also like to add a path argument to stream_read, stream_read_entire, stream_write, stream_seek and stream_tell, so that the path information is available when a StreamError is raised.

I am working on it ATM.

**Pull request closed without merging**
