### PR TITLE
Remove obsolete metadata entries.

### LINKED ISSUE #757: Remove deprecated "requires" from setup.py
The presence of `requires` in setup.py together with `install_requires` breaks builds with the most recent releases of _wheel_ when used with _distlib_. The `requires` entry in setup.py produces `Requires` in metadata file, and `install_requires` produces `Requires-Dist`. The change has been done in [PEP 345](https://www.python.org/dev/peps/pep-0345/) over 13 years ago. Presence of both fields in the metadata file is not accepted by _distlib_ any more.

Namely, _wheel_ >= 0.31.0 uses metadata format 2.1 and _distlib_ has adapted to that change. Notice also that wheel-0.31.1 is required by the most recent releases of virtualenv (16.0.0) and pip (18.0). Among them, _distlib_ is the most strict in what it considers as correct metadata. See the recent issue and _distlib_ author's reply: https://bitbucket.org/pypa/distlib/issues/106/support-21-metadata
This led to other issues similar to the one I'm opening here:
* https://github.com/dateutil/dateutil/issues/720
* https://github.com/pypa/setuptools/issues/1396

Fortunately, the current version of _construct_'s setup.py has both of these entries empty: https://github.com/construct/construct/blob/master/setup.py#L28
Thus, neither of these fields is recorded into metadata.
The older versions, though, had both entries populated: https://github.com/construct/construct/blob/v2.5.2/setup.py#L36
This did leak into metadata and caused exceptions with _distlib_ (debug logging turned on):
```
DEBUG:distlib.metadata:Removed 1.0 due to Requires-Dist
DEBUG:distlib.metadata:Removed 1.1 due to Requires-Dist
DEBUG:distlib.metadata:Removed 1.2 due to Provides
DEBUG:distlib.metadata:Removed 1.3 due to Provides
DEBUG:distlib.metadata:Removed 2.1 due to Provides
DEBUG:distlib.metadata:Removed 2.0 due to Provides
DEBUG:distlib.metadata:Out of options - unknown metadata set: {'Metadata-Version': '2.1', 'Author': 'Tomer Filiba, Corbin Simpson', 'Version': '2.5.2', 'Requires-Dist': ['six'], 'Platform': ['POSIX', 'Windows'], 'Provides': ['construct'], 'Requires': ['six'], 'Classifier': ['Development Status :: 5 - Production/Stable', 'License :: OSI Approved :: MIT License', 'Programming Language :: Python :: 2.5', 'Programming Language :: Python :: 2.6', 'Programming Language :: Python :: 2.7', 'Programming Language :: Python :: 3', 'Programming Language :: Python :: 3.0', 'Programming Language :: Python :: 3.1', 'Programming Language :: Python :: 3.2', 'Programming Language :: Python :: 3.3'], 'Author-email': 'tomerfiliba@gmail.com, MostAwesomeDude@gmail.com', 'License': 'MIT', 'Summary': 'A powerful declarative parser/builder for binary data', 'Keywords': ['construct', 'declarative', 'data structure', 'binary', 'parser', 'builder', 'pack', 'unpack'], 'Home-page': 'http://construct.readthedocs.org', 'Name': 'construct'}
```
The presence of both `Requires` and `Requires-Dist` is the same as the issues referenced above.

Can `requires` be removed from setup.py to ensure this does not happen in the future?

### PR DESCRIPTION
**Pull request by zvezdan**
The "requires" and "provides" entries in setup.py produce "Requires" and
"Provides" fields in metadata files. These fields have been replaced by
"Requires-Dist" and "Provides-Dist" in PEP 345 thirteen years ago.
Recently they started causing issues with latest wheel releases
producing Metadata 2.1 format and distlib refusing to accept these
fields in a modern metadata format.

This small patch fixes #757.

### CODE REVIEW

**Comment by zvezdan** [comment]
My change passes all the checks except Python 3.3 and that one is not related to my change. :-)
```
Downloading https://files.pythonhosted.org/packages/75/a2/00ff9e552299bc8cec183eafa3fce01cfc1c002e2d838d70bb174f9e5c9f/ruamel.yaml-0.15.71.tar.gz (309kB)
   ...
    Complete output from command python setup.py egg_info:
    minimum python version(s): [(2, 7), (3, 4)]
```
Obviously, `ruamel.yaml` will not work with Python < 3.4 and that's reasonable.
Python 3.3 should be dropped from supported versions.

Can someone do that for Travis CI or just merge the change?

**Comment by arekbulski** [comment]
You can simply edit the .travis file and remove 3.3 or whatever is needed, then commit this to the PR branch. The travis configuration is entirely contained in a file in this repository, its not on some webpage on some .com somewhere.

**Comment by zvezdan** [comment]
@arekbulski I know where travis configs reside.

I did not want to mix two unrelated commits.

My change is fixing the incompatibility of this package with modern Python packaging tooling that causes issues to consumers.

The travis config change is a generic change that needs to be done on your package anyway *unrelated* to this change.

I'll do it this time, but ...

**Comment by arekbulski** [comment]
You missed the pypi manifest:
https://github.com/construct/construct/blob/33e11de1356224aea096a8d8fee39d4f03c5ee06/setup.py#L55

**Comment by zvezdan** [comment]
Done.

**Pull request merged**
